### ISSUE TITLE
Content missining

### ISSUE THREAD

**Issue by 33windowlicker** [infinum/rails-handbook#11]
- https://github.com/infinum/rails-handbook/blob/master/Automated%20Testing.md
- https://github.com/infinum/rails-handbook/blob/master/Building%20an%20API.md
- https://github.com/infinum/rails-handbook/blob/master/Continous%20Integration.md
- https://github.com/infinum/rails-handbook/blob/master/Bug%20Tracking.md
- https://github.com/infinum/rails-handbook/blob/master/Handbook%20Editing%20Guideline.md

**Comment by DamirSvrtan** [comment]
@33windowlicker - please write everything in english.
